config/routes.rb
Rails.application.routes.draw do
  resources :provinces

  resources :customers

  root 'finder#index'

  get 'alphabetize' => 'finder#alphabetize'

  get 'missing_email' => 'finder#missing_email'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  validates :full_name, :image, presence: true
  def self.provinces_for_select
    provinces = all
    descriptions = [['All', 0]]
    provinces.each do |row|
      descriptions << [row.name,row.id]
    end
    descriptions
  end
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers

  def self.provinces_for_select
    provinces = all
    descriptions = []
    provinces.each do |row|
      descriptions << [row.name,row.id]
    end
    descriptions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @provinces_for_select = Province.provinces_for_select
  end

  # GET /customers/1/edit
  def edit
    @provinces_for_select = Province.provinces_for_select
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @provinces_for_select = Province.provinces_for_select
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:full_name, :phone_number, :email, :image, :notes, :province_id)
    end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @customers = Customer.all
    @provinces_for_select = Province.provinces_for_select
  end

  def alphabetize
    @alpha = Customer.order('full_name ASC')
  end

  def missing_email
    @missing_email = Customer.where("email is null OR email = ''")
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/customers/_customer.html.erb
<p>
  <%= link_to 'edit', edit_customer_path(customer) %>
  <%= link_to 'x', customer, data:{confirm: 'Are you sure you wish to delete?'}, method: :delete %>
<p>
<h1><%= customer.full_name %></h1>
<p><%= image_tag customer.image, width:250 %></p>
<p><%= customer.phone_number %></p>
<p><%= customer.email %></p>
<p><%= customer.notes %></p>
<p>
  <% if customer.province_id != nil %>
    <p><%= customer.province_id %></p>
  <% else %>
    <p>Province: None</p>
  <% end %>
<%= customer.inspect %>
</p>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
    <div class="field">
      <%= select_tag(:category_id, options_for_select(@provinces_for_select)) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Image</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.full_name %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.email %></td>
        <td><%= customer.image %></td>
        <td><%= customer.notes %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

<%= render @customers %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @customer.full_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Image:</strong>
  <%= @customer.image %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer.notes %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/finder/alphabetize.html.erb
<%= render @alpha %>

app/views/finder/index.html.erb
<%= link_to 'Missing Emails', missing_email_path %>
<%= render @customers %>

app/views/finder/missing_email.html.erb
<%= link_to 'Index', root_path %>
<%= render @missing_email %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>